defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Shizhe Hu
subtitle: Associate Research Fellow  <br/>Master Supervisor</br>   

# left_side:
background_image: "./assets/ShizheHu.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"


# Side Menu Links
menu:
  - text: News
    link: /
    icon: ""

  - text: Brief Bio
    link: /Brief-Bio
    icon: ""

  - text: Fundings
    link: /Fundings
    icon: ""

  - text: Journal Papers
    link: /Journal-Papers
    icon: ""

  - text: Conference Papers
    link: /Conference-Papers
    icon: ""
    
  - text: Academic Activities
    link: /Academic-Activities
    icon: ""
  
  - text: Awards and Honors
    link: /Awards-Honors
    icon: ""
    





# Socialmedia Icons
social_icons:
  - name: mail
    link: mailto:ieshizhehu@zzu.edu.cn
    icon: icon brands fa fa-envelope

  - name: google scholar
    link: https://scholar.google.com/citations?user=AwzvxQEAAAAJ&hl=en&authuser=1&oi=ao
    icon: fab fa-google

  - name: github
    link: https://github.com/ShizheHu
    icon: fab fa-github-square


    
